// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Chebi                string
	Compound             string
	Genbank              string
	GenbankFeatures      string
	Reaction             string
	ReactionParticipant  string
	Reactionside         string
	ReactionsideReaction string
	ReactivePart         string
	Seqhash              string
	Uniprot              string
	UniprotToReaction    string
}{
	Chebi:                "chebi",
	Compound:             "compound",
	Genbank:              "genbank",
	GenbankFeatures:      "genbank_features",
	Reaction:             "reaction",
	ReactionParticipant:  "reaction_participant",
	Reactionside:         "reactionside",
	ReactionsideReaction: "reactionside_reaction",
	ReactivePart:         "reactive_part",
	Seqhash:              "seqhash",
	Uniprot:              "uniprot",
	UniprotToReaction:    "uniprot_to_reaction",
}
